// Generated by CoffeeScript 1.7.1
(function() {
  var Solve, test1, test2, test3, test4;

  Solve = function(args) {
    var countOfNumbers, i, number, numberOfSequences, numbers, sequences, _i, _len, _ref;
    _ref = [Number(args[0]), args.slice(1).map(Number)], countOfNumbers = _ref[0], numbers = _ref[1];
    sequences = [[]];
    numberOfSequences = 0;
    for (i = _i = 0, _len = numbers.length; _i < _len; i = ++_i) {
      number = numbers[i];
      sequences[numberOfSequences].push(number);
      if (number > numbers[i + 1]) {
        numberOfSequences++;
        sequences[numberOfSequences] = [];
      }
    }
    if (numberOfSequences > 0) {
      numberOfSequences++;
    }
    return numberOfSequences;
  };

  test1 = ["7", "1", "2", "-3", "4", "4", "0", "1"];

  test2 = ["6", "1", "3", "-5", "8", "7", "-6"];

  test3 = ["9", "1", "8", "8", "7", "6", "5", "7", "7", "6"];

  test4 = [];

  console.log(Solve(test1));

  console.log(Solve(test2));

  console.log(Solve(test3));

  console.log(Solve(test4));


  /*
    input =
    calculations =
    output =
   */

}).call(this);
