// Generated by CoffeeScript 1.7.1
(function() {
  require(['BullsAndCows', 'BullsAndCowsUI', 'jquery', 'Storage'], function(BullsAndCows, UI, $, Storage) {
    var container, endGame, gameManager, makeGuess, startNewGame, updateHighScores;
    container = new UI('#game');
    gameManager = new BullsAndCows();
    updateHighScores = function(score) {
      var highScores, name, storage;
      name = $('.hi-score-name').val();
      storage = new Storage();
      highScores = storage.getStorage();
      highScores = gameManager.updateHighScores({
        name: name,
        score: score
      }, highScores);
      storage.setStorage(highScores);
      container.drawHighScores(highScores);
      container.drawStartScreen();
      return $('.btn-start-new-game').focus().click(startNewGame);
    };
    endGame = function(score) {
      container.drawWinScreen(score);
      $('.add-name').click(function() {
        return updateHighScores(score);
      });
      return $('.hi-score-name').focus().keypress(function(key) {
        if (key.which === 13) {
          return $('.add-name').focus().click();
        }
      });
    };
    makeGuess = function() {
      var guessedNumber, result;
      guessedNumber = $('.input').val();
      $('.input').val('');
      if (gameManager.isNumberValid(guessedNumber)) {
        result = gameManager.makeGuess(guessedNumber);
        container.drawGuess(result);
        if (result.bulls === 4) {
          return endGame(gameManager.getGuesses());
        }
      } else {
        return console.error("Wrong number: '" + guessedNumber + "'");
      }
    };
    startNewGame = function() {
      gameManager.startGame();
      container.drawGameScreen();
      $('.btn-make-guess').click(makeGuess);
      return $('.input').focus().keypress(function(key) {
        if (key.which === 13) {
          return $('.btn-make-guess').click();
        }
      });
    };
    container.drawStartScreen();
    return $('.btn-start-new-game').focus().click(startNewGame);
  });

}).call(this);
