// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var RNG;
    return RNG = (function() {
      function RNG() {}

      RNG.prototype.getInteger = function(min, max) {
        if (min == null) {
          min = 0;
        }
        if (max == null) {
          max = 9;
        }
        return min + Math.random() * (max - min + 1) >> 0;
      };

      RNG.prototype.getSecretNumber = function() {
        var digits, i, secretNumber, _i;
        digits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
        secretNumber = '';
        secretNumber += digits.splice(this.getInteger(1, 9), 1);
        for (i = _i = 1; _i <= 3; i = ++_i) {
          secretNumber += digits.splice(this.getInteger(0, 9 - i), 1);
        }
        return secretNumber;
      };

      return RNG;

    })();
  });

}).call(this);
