// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var Storage;
    return Storage = (function() {
      function Storage() {}

      Storage.prototype.getStorage = function() {
        return JSON.parse(localStorage.getItem('highScores')) || [];
      };

      Storage.prototype.setStorage = function(highScores) {
        return localStorage.setItem('highScores', JSON.stringify(highScores));
      };

      return Storage;

    })();
  });

}).call(this);
