// Generated by CoffeeScript 1.7.1
(function() {
  var a, b, bigNumber, c, digit, englishNumber, englishOnes, englishTeens, englishTens, num, numbers, print, printBiggestNumber, productSign, quadraticSolutions, randomInt, word, x1, x2, _i, _len, _ref, _ref1, _ref2, _ref3, _ref4,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  randomInt = function(min, max) {
    if (min == null) {
      min = 0;
    }
    if (max == null) {
      max = 100;
    }
    return min + Math.random() * (max - min + 1) >> 0;
  };

  print = function(str) {
    return document.writeln("" + str + " <br />");
  };

  printBiggestNumber = function(numbers) {
    var maxNumber, num, _i, _len;
    maxNumber = num[0];
    for (_i = 0, _len = numbers.length; _i < _len; _i++) {
      num = numbers[_i];
      if (num > maxNumber) {
        maxNumber = num;
      }
    }
    return print("The biggest of the numbers " + numbers + " is " + maxNumber);
  };

  print("Task 1:");

  a = randomInt();

  b = randomInt();

  print("a = " + a + ", b = " + b);

  if (a > b) {
    _ref = [b, a], a = _ref[0], b = _ref[1];
  }

  print("After comparison:");

  print("a = " + a + ", b = " + b);

  print("<br />Task 2:");

  numbers = (function() {
    var _i, _results;
    _results = [];
    for (a = _i = 1; _i <= 3; a = ++_i) {
      _results.push(randomInt(-10, 10));
    }
    return _results;
  })();

  productSign = 0;

  for (_i = 0, _len = numbers.length; _i < _len; _i++) {
    num = numbers[_i];
    if (num < 0) {
      productSign = productSign ^ 1;
    }
  }

  productSign = __indexOf.call(numbers, 0) >= 0 ? 'none' : productSign === 0 ? 'plus' : 'minus';

  print("The sign of the product of the numbers " + numbers + " is " + productSign);

  print("<br />Task 3:");

  printBiggestNumber(numbers);

  print("<br />Task 4:");

  print("Unsorted array: " + numbers);

  if (numbers[0] > numbers[1]) {
    _ref1 = [numbers[1], numbers[0]], numbers[0] = _ref1[0], numbers[1] = _ref1[1];
  }

  if (numbers[1] > numbers[2]) {
    _ref2 = [numbers[2], numbers[1]], numbers[1] = _ref2[0], numbers[2] = _ref2[1];
  }

  if (numbers[0] > numbers[1]) {
    _ref3 = [numbers[1], numbers[2]], numbers[0] = _ref3[0], numbers[1] = _ref3[1];
  }

  print("Sorted array: " + numbers);

  print("<br />Task 5:");

  digit = randomInt(0, 9);

  word = (function() {
    switch (digit) {
      case 0:
        return "Zero";
      case 1:
        return "One";
      case 2:
        return "Two";
      case 3:
        return "Three";
      case 4:
        return "Four";
      case 5:
        return "Five";
      case 6:
        return "Six";
      case 7:
        return "Seven";
      case 8:
        return "Eight";
      case 9:
        return "Nine";
      default:
        return "Invalid digit!";
    }
  })();

  print("Digit: " + digit);

  print("Word: " + word);

  print("<br />Task 6:");

  a = randomInt(0, 10);

  b = randomInt(0, 10);

  c = randomInt(0, 10);

  print("Coefficients are: " + a + ", " + b + ", " + c);

  x1 = -b / 2 / a + Math.pow(Math.pow(b, 2) - 4 * a * c, 0.5) / 2 / a;

  x2 = -b / 2 / a - Math.pow(Math.pow(b, 2) - 4 * a * c, 0.5) / 2 / a;

  quadraticSolutions = isNaN(x1) ? 0 : x1 === x2 ? 1 : 2;

  print(("The equation has " + quadraticSolutions + " solutions") + (function() {
    switch (quadraticSolutions) {
      case 0:
        return "";
      case 1:
        return ", which is: " + x1;
      case 2:
        return ", which are: " + x1 + ", " + x2;
    }
  })());

  print("<br />Task 7:");

  printBiggestNumber((function() {
    var _j, _results;
    _results = [];
    for (a = _j = 1; _j <= 5; a = ++_j) {
      _results.push(randomInt());
    }
    return _results;
  })());

  print("<br />Task 8:");

  bigNumber = randomInt(0, 999);

  englishOnes = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"];

  englishTeens = ["Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"];

  englishTens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"];

  englishNumber = "";

  if (bigNumber >= 100) {
    englishNumber += englishOnes[Math.floor(bigNumber / 100)] + " hundred ";
    if ((0 < (_ref4 = bigNumber % 100) && _ref4 < 20) || bigNumber % 10 === 0) {
      englishNumber += "and ";
    }
  }

  if (bigNumber === 0) {
    englishNumber = "Zero";
  } else if (bigNumber % 100 >= 20) {
    englishNumber += englishTens[Math.floor(bigNumber / 10) % 10] + " " + englishOnes[bigNumber % 10];
  } else if (bigNumber % 100 >= 10) {
    englishNumber += englishTeens[bigNumber % 10];
  } else {
    englishNumber += englishOnes[bigNumber % 10];
  }

  print("Number: " + bigNumber);

  print("Word: " + englishNumber);

}).call(this);
