// Generated by CoffeeScript 1.7.1
(function() {
  var Solve, test1;

  Solve = function(args) {
    var content, html, i, ifHtml, ifName, inIf, inTemplate, key, line, models, modelsCount, newLine, templateHtml, templateLine, templateName, templates, value, view, viewCount, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _len6, _m, _n, _o, _p, _q, _ref;
    modelsCount = Number(args[0]);
    models = {};
    for (i = _i = 1; 1 <= modelsCount ? _i <= modelsCount : _i >= modelsCount; i = 1 <= modelsCount ? ++_i : --_i) {
      key = args[i].split("-")[0];
      value = args[i].split("-")[1].split(";");
      models[key] = value;
    }
    viewCount = args[modelsCount + 1];
    view = [];
    for (i = _j = 0; 0 <= viewCount ? _j < viewCount : _j > viewCount; i = 0 <= viewCount ? ++_j : --_j) {
      view[i] = args[modelsCount + i + 2];
    }
    templates = [];
    inTemplate = false;
    html = [];
    for (_k = 0, _len = view.length; _k < _len; _k++) {
      line = view[_k];
      if (line.indexOf('</nk-template>') !== -1) {
        inTemplate = false;
      }
      if (inTemplate) {
        templates[templateName].push(line);
      }
      if (line.indexOf('<nk-template name=') !== -1) {
        inTemplate = true;
        templateName = line.substring(line.indexOf('"') + 1, line.lastIndexOf('"'));
        templates[templateName] = [];
      }
      if (line.indexOf('<nk-template name=') === -1 && line.indexOf('</nk-template>') === -1 && !inTemplate) {
        html.push(line);
      }
    }
    for (i = _l = 0, _len1 = html.length; _l < _len1; i = ++_l) {
      line = html[i];
      newLine = line;
      while (newLine.indexOf('<nk-model>', newLine.indexOf('}}')) !== -1 || newLine.substring(0, newLine.indexOf('{{')).indexOf('<nk-model>') !== -1) {
        key = newLine.substring(newLine.indexOf('<nk-model>') + 10, newLine.indexOf('</nk-model>'));
        newLine = newLine.replace("<nk-model>" + key + "</nk-model>", models[key]);
      }
      html[i] = newLine;
    }
    templateHtml = [];
    for (_m = 0, _len2 = html.length; _m < _len2; _m++) {
      line = html[_m];
      if (line.indexOf('<nk-template render=') !== -1) {
        templateName = line.substring(line.indexOf('"') + 1, line.lastIndexOf('"'));
        _ref = templates[templateName];
        for (_n = 0, _len3 = _ref.length; _n < _len3; _n++) {
          templateLine = _ref[_n];
          templateHtml.push(templateLine);
        }
      } else {
        templateHtml.push(line);
      }
    }
    inIf = false;
    ifHtml = [];
    for (_o = 0, _len4 = templateHtml.length; _o < _len4; _o++) {
      line = templateHtml[_o];
      if (line.indexOf('</nk-if>') !== -1) {
        inIf = false;
      }
      if (line.indexOf('<nk-if') !== -1) {
        ifName = line.substring(line.indexOf('"') + 1, line.lastIndexOf('"'));
        if (!JSON.parse(models[ifName])) {
          inIf = true;
        }
      }
      if (line.indexOf('<nk-if') === -1 && line.indexOf('</nk-if>') === -1 && !inIf) {
        ifHtml.push(line);
      }
    }
    for (i = _p = 0, _len5 = ifHtml.length; _p < _len5; i = ++_p) {
      line = ifHtml[i];
      newLine = line;
      while (newLine.indexOf('{{') !== -1) {
        content = newLine.substring(newLine.indexOf('{{') + 2, newLine.indexOf('}}'));
        newLine = newLine.replace("{{" + content + "}}", content);
      }
      ifHtml[i] = newLine;
    }
    for (_q = 0, _len6 = ifHtml.length; _q < _len6; _q++) {
      line = ifHtml[_q];
      console.log(line);
    }
  };

  test1 = ['6', 'title-Telerik Academy', 'showSubtitle-true', 'subTitle-Free training', 'showMarks-false', 'marks-3;4;5;6', 'students-Ivan;Gosho;Pesho', '42', '<nk-template name="menu">', '    <ul id="menu">', '        <li>Home</li>', '        <li>About us</li>', '    </ul>', '</nk-template>', '<nk-template name="footer">', '    <footer>', '        Copyright Telerik Academy 2014', '    </footer>', '</nk-template>', '<!DOCTYPE html>', '<html>', '<head>', '    <title>Telerik Academy</title>', '</head>', '<body>', '    <nk-template render="menu" />', '', '    <h1><nk-model>title</nk-model></h1>', '    <nk-if condition="showSubtitle">', '        <h2><nk-model>subTitle</nk-model></h2>', '        <div>{{<nk-model>subTitle</nk-model>}} ;)</div>', '    </nk-if>', '', '    <ul>', '        <nk-repeat for="student in students">', '            <li>', '                <nk-model>student</nk-model>', '            </li>', '            <li>Multiline <nk-model>title</nk-model></li>', '        </nk-repeat>', '    </ul>', '    <nk-if condition="showMarks">', '        <div>', '            <nk-model>marks</nk-model> ', '        </div>', '    </nk-if>', '', '    <nk-template render="footer" />', '</body>', '</html>'];

  Solve(test1);

}).call(this);
