// Generated by CoffeeScript 1.7.1
define([], function() {
  var Animal;
  Animal = (function() {
    function Animal(specie, legs) {
      this.specie = specie;
      this.legs = legs;
    }

    return Animal;

  })();
  return Animal;
});

//# sourceMappingURL=animal.map
