// Generated by CoffeeScript 1.7.1
define([], function() {
  var Book;
  Book = (function() {
    function Book(author, title) {
      this.author = author;
      this.title = title;
    }

    return Book;

  })();
  return Book;
});

//# sourceMappingURL=book.map
