// Generated by CoffeeScript 1.7.1
define([], function() {
  var Person;
  Person = (function() {
    function Person(firstName, lastName) {
      this.firstName = firstName;
      this.lastName = lastName;
    }

    return Person;

  })();
  return Person;
});

//# sourceMappingURL=person.map
