// Generated by CoffeeScript 1.7.1
define([], function() {
  var Student;
  Student = (function() {
    function Student(firstName, lastName, age, marks) {
      this.firstName = firstName;
      this.lastName = lastName;
      this.age = age;
      this.marks = marks;
    }

    return Student;

  })();
  return Student;
});

//# sourceMappingURL=student.map
