// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery'], function($) {
    var studentModel;
    return studentModel = (function() {
      function studentModel() {
        this.url = 'http://localhost:3000/students';
      }

      studentModel.prototype.getAllStudents = function(success, error) {
        return $.ajax({
          url: this.url,
          type: 'GET',
          contentType: 'application/json',
          success: success,
          error: error
        });
      };

      studentModel.prototype.createNewStudent = function(student, success, error) {};

      studentModel.prototype.removeStudent = function(id, success, error) {};

      return studentModel;

    })();
  });

}).call(this);
