// Generated by CoffeeScript 1.7.1
(function() {
  var TypeOf, hiThisIsBoolean, hiThisIsFloat, hiThisIsInteger, hiThisIsNull, hiThisIsString, hiThisIsUndefined, howYouDoin;

  hiThisIsInteger = 42;

  hiThisIsFloat = 3.14;

  hiThisIsBoolean = false;

  hiThisIsString = "And then there were none ...";

  howYouDoin = "\"How you doin'?\", Joey said.";

  TypeOf = function(x) {
    document.writeln(("'" + x + "' is of type ") + typeof x + "<br />");
  };

  TypeOf(hiThisIsInteger);

  TypeOf(hiThisIsFloat);

  TypeOf(hiThisIsBoolean);

  TypeOf(hiThisIsString);

  hiThisIsNull = null;

  hiThisIsUndefined = void 0;

  TypeOf(hiThisIsNull);

  TypeOf(hiThisIsUndefined);

}).call(this);
