// Generated by CoffeeScript 1.7.1
(function() {
  var occurancesInString, print, randomInt, randomNumber, text, word;

  randomInt = function(min, max) {
    if (min == null) {
      min = 0;
    }
    if (max == null) {
      max = 100;
    }
    return min + Math.random() * (max - min + 1) >> 0;
  };

  print = function(str) {
    return document.writeln("" + str + " <br />");
  };

  occurancesInString = function(word, text, sensitive) {
    var pattern;
    if (sensitive == null) {
      sensitive = false;
    }
    pattern = "/\b" + word + "\b/g";
    return text.match(pattern);
  };

  print("Task 1:");

  randomNumber = randomInt(0, 1000);

  word = (function() {
    switch (randomNumber % 10) {
      case 0:
        return "Zero";
      case 1:
        return "One";
      case 2:
        return "Two";
      case 3:
        return "Three";
      case 4:
        return "Four";
      case 5:
        return "Five";
      case 6:
        return "Six";
      case 7:
        return "Seven";
      case 8:
        return "Eight";
      case 9:
        return "Nine";
      default:
        return "Invalid digit!";
    }
  })();

  print("Random number: : " + randomNumber);

  print("Last digit: " + word);

  print("<br />Task 2:");

  print(Number(randomNumber.toString().split("").reverse().join("")));

  print("<br />Task 3:");

  text = "as asdf, zxc? asdf!";

  print(occurancesInString("asdf", text));

}).call(this);
