-- MySQL Script generated by MySQL Workbench
-- 08/24/14 13:06:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Faculties` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Faculties` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Faculty` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Department` VARCHAR(45) NOT NULL,
  `Faculties_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Departments_Faculties_idx` (`Faculties_Id` ASC),
  CONSTRAINT `fk_Departments_Faculties`
    FOREIGN KEY (`Faculties_Id`)
    REFERENCES `mydb`.`Faculties` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Departments_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Professors_Departments1_idx` (`Departments_Id` ASC),
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`Departments_Id`)
    REFERENCES `mydb`.`Departments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Titles` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors_has_Titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professors_has_Titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professors_has_Titles` (
  `Professors_Id` INT NOT NULL,
  `Titles_Id` INT NOT NULL,
  PRIMARY KEY (`Professors_Id`, `Titles_Id`),
  INDEX `fk_Professors_has_Titles_Titles1_idx` (`Titles_Id` ASC),
  INDEX `fk_Professors_has_Titles_Professors1_idx` (`Professors_Id` ASC),
  CONSTRAINT `fk_Professors_has_Titles_Professors1`
    FOREIGN KEY (`Professors_Id`)
    REFERENCES `mydb`.`Professors` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_has_Titles_Titles1`
    FOREIGN KEY (`Titles_Id`)
    REFERENCES `mydb`.`Titles` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Course` VARCHAR(45) NOT NULL,
  `Departments_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Courses_Departments1_idx` (`Departments_Id` ASC),
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`Departments_Id`)
    REFERENCES `mydb`.`Departments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors_has_Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professors_has_Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professors_has_Courses` (
  `Professors_Id` INT NOT NULL,
  `Courses_Id` INT NOT NULL,
  PRIMARY KEY (`Professors_Id`, `Courses_Id`),
  INDEX `fk_Professors_has_Courses_Courses1_idx` (`Courses_Id` ASC),
  INDEX `fk_Professors_has_Courses_Professors1_idx` (`Professors_Id` ASC),
  CONSTRAINT `fk_Professors_has_Courses_Professors1`
    FOREIGN KEY (`Professors_Id`)
    REFERENCES `mydb`.`Professors` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_has_Courses_Courses1`
    FOREIGN KEY (`Courses_Id`)
    REFERENCES `mydb`.`Courses` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Faculties_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Students_Faculties1_idx` (`Faculties_Id` ASC),
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`Faculties_Id`)
    REFERENCES `mydb`.`Faculties` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses_has_Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses_has_Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses_has_Students` (
  `Courses_Id` INT NOT NULL,
  `Students_Id` INT NOT NULL,
  PRIMARY KEY (`Courses_Id`, `Students_Id`),
  INDEX `fk_Courses_has_Students_Students1_idx` (`Students_Id` ASC),
  INDEX `fk_Courses_has_Students_Courses1_idx` (`Courses_Id` ASC),
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`Courses_Id`)
    REFERENCES `mydb`.`Courses` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`Students_Id`)
    REFERENCES `mydb`.`Students` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
