-- MySQL Script generated by MySQL Workbench
-- 08/23/14 11:02:53
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MultilingualDictionary
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MultilingualDictionary` ;
CREATE SCHEMA IF NOT EXISTS `MultilingualDictionary` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MultilingualDictionary` ;

-- -----------------------------------------------------
-- Table `MultilingualDictionary`.`Languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultilingualDictionary`.`Languages` ;

CREATE TABLE IF NOT EXISTS `MultilingualDictionary`.`Languages` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultilingualDictionary`.`Words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultilingualDictionary`.`Words` ;

CREATE TABLE IF NOT EXISTS `MultilingualDictionary`.`Words` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Word` VARCHAR(45) NOT NULL,
  `Languages_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Languages_Id`),
  INDEX `fk_Words_Languages1_idx` (`Languages_Id` ASC),
  CONSTRAINT `fk_Words_Languages1`
    FOREIGN KEY (`Languages_Id`)
    REFERENCES `MultilingualDictionary`.`Languages` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultilingualDictionary`.`Synonyms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultilingualDictionary`.`Synonyms` ;

CREATE TABLE IF NOT EXISTS `MultilingualDictionary`.`Synonyms` (
  `Words_Id` INT NOT NULL,
  `Words_Id1` INT NOT NULL,
  PRIMARY KEY (`Words_Id`, `Words_Id1`),
  INDEX `fk_Words_has_Words_Words2_idx` (`Words_Id1` ASC),
  INDEX `fk_Words_has_Words_Words1_idx` (`Words_Id` ASC),
  CONSTRAINT `fk_Words_has_Words_Words1`
    FOREIGN KEY (`Words_Id`)
    REFERENCES `MultilingualDictionary`.`Words` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Words_has_Words_Words2`
    FOREIGN KEY (`Words_Id1`)
    REFERENCES `MultilingualDictionary`.`Words` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultilingualDictionary`.`TranslationWords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultilingualDictionary`.`TranslationWords` ;

CREATE TABLE IF NOT EXISTS `MultilingualDictionary`.`TranslationWords` (
  `Words_Id` INT NOT NULL,
  `Words_Id1` INT NOT NULL,
  PRIMARY KEY (`Words_Id`, `Words_Id1`),
  INDEX `fk_Words_has_Words_Words4_idx` (`Words_Id1` ASC),
  INDEX `fk_Words_has_Words_Words3_idx` (`Words_Id` ASC),
  CONSTRAINT `fk_Words_has_Words_Words3`
    FOREIGN KEY (`Words_Id`)
    REFERENCES `MultilingualDictionary`.`Words` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Words_has_Words_Words4`
    FOREIGN KEY (`Words_Id1`)
    REFERENCES `MultilingualDictionary`.`Words` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultilingualDictionary`.`Explanations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultilingualDictionary`.`Explanations` ;

CREATE TABLE IF NOT EXISTS `MultilingualDictionary`.`Explanations` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Explanation` TEXT NOT NULL,
  `Words_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Words_Id`),
  INDEX `fk_Explanations_Words1_idx` (`Words_Id` ASC),
  CONSTRAINT `fk_Explanations_Words1`
    FOREIGN KEY (`Words_Id`)
    REFERENCES `MultilingualDictionary`.`Words` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
