// Generated by CoffeeScript 1.7.1
(function() {
  var Mod, a, b, c, f, mod, numbers, sum, _i, _ref,
    __slice = [].slice;

  sum = function() {
    var num, _i, _results;
    sum = 0;
    _results = [];
    for (num = _i = 0; _i <= 1000; num = ++_i) {
      _results.push(sum += num);
    }
    return _results;
  };

  numbers = [0, 1, 2, 3, 4];

  Mod = function() {
    var log;
    return log = function() {
      return console.log(3);
    };
  };

  mod = new Mod();

  _ref = "ABCDEF", a = _ref[0], b = _ref[1], c = 4 <= _ref.length ? __slice.call(_ref, 2, _i = _ref.length - 1) : (_i = 2, []), f = _ref[_i++];

  console.log(a, b, c, f);

}).call(this);
