// Generated by CoffeeScript 1.7.1
(function() {
  var compareStrings, index, maxSequenceOfEqualElements, print, randomInt, str1, str2;

  randomInt = function(min, max) {
    if (min == null) {
      min = 0;
    }
    if (max == null) {
      max = 100;
    }
    return min + Math.random() * (max - min + 1) >> 0;
  };

  print = function(str) {
    return document.writeln("" + str + " <br />");
  };

  print("Task 1:");

  print("Array: " + ((function() {
    var _i, _results;
    _results = [];
    for (index = _i = 0; _i < 20; index = ++_i) {
      _results.push(index * 5);
    }
    return _results;
  })()));

  print("<br />Task 2:");

  str1 = "pesho";

  str2 = "gosho";

  compareStrings = function(str1, str2) {
    var chr, i, _i, _len;
    if (str1.length !== str2.length) {
      return false;
    }
    for (i = _i = 0, _len = str1.length; _i < _len; i = ++_i) {
      chr = str1[i];
      if (chr !== str2[i]) {
        return false;
      }
    }
    return true;
  };

  print(("Are the two character arrays \"" + str1 + "\" and \"" + str2 + "\" equal: ") + compareStrings(str1, str2));

  print("<br/ >Task 3:");

  maxSequenceOfEqualElements = function(arr) {
    var maxCount, maxElement;
    maxCount = 0;
    return maxElement = null;
  };

}).call(this);
