// Generated by CoffeeScript 1.7.1
(function() {
  define(['httpRequester'], function(httpRequester) {
    var httpReq;
    httpReq = new httpRequester();
    return httpReq.getJSON();
  });

}).call(this);
