// Generated by CoffeeScript 1.7.1
(function() {
  define(['jQuery', '../bower_components/q/q', 'underscore'], function($, Q, _) {
    var httpRequester;
    return httpRequester = (function() {
      function httpRequester() {}

      httpRequester.prototype.getJSON = function(url, headers, success, error) {
        return $.ajax({
          url: url,
          type: 'GET',
          header: headers,
          success: success,
          error: error
        });
      };

      httpRequester.prototype.postJSON = function(url, headers) {};

      return httpRequester;

    })();
  });

}).call(this);
