// Generated by CoffeeScript 1.7.1
(function() {
  var Solve, test1, test2, test3, test4, test5;

  Solve = function(args) {
    var C1, C2, C3, S, a, b, c, maxSpent, spent, _i, _j, _k, _ref, _ref1, _ref2, _ref3;
    _ref = args.map(Number), S = _ref[0], C1 = _ref[1], C2 = _ref[2], C3 = _ref[3];
    maxSpent = 0;
    spent = 0;
    for (a = _i = 0, _ref1 = S / C1; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; a = 0 <= _ref1 ? ++_i : --_i) {
      spent = a * C1;
      if (spent > S) {
        continue;
      }
      for (b = _j = 0, _ref2 = S / C2; 0 <= _ref2 ? _j <= _ref2 : _j >= _ref2; b = 0 <= _ref2 ? ++_j : --_j) {
        spent = a * C1 + b * C2;
        if (spent > S) {
          continue;
        }
        for (c = _k = 0, _ref3 = S / C3; 0 <= _ref3 ? _k <= _ref3 : _k >= _ref3; c = 0 <= _ref3 ? ++_k : --_k) {
          spent = a * C1 + b * C2 + c * C3;
          if (spent > S) {
            continue;
          }
          if (spent > maxSpent) {
            maxSpent = spent;
          }
        }
      }
    }
    return maxSpent;
  };

  test1 = ["110", "13", "15", "17"];

  test2 = ["20", "11", "200", "300"];

  test3 = ["110", "19", "29", "39"];

  test4 = ["1", "11", "12", "13"];

  test5 = ["21", "11", "12", "13"];

  console.log(Solve(test1));

  console.log(Solve(test2));

  console.log(Solve(test3));

  console.log(Solve(test4));

  console.log(Solve(test5));

}).call(this);
