// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'jquery', 'sha1', 'http-requester', 'persister', 'controller', 'ui'], function(_, $, CryptoJS, httpRequester, Persister, Controller, UI) {});

}).call(this);
