// Generated by CoffeeScript 1.7.1
(function() {
  define(["todo-list/section"], function(Section) {
    var Container;
    return Container = (function() {
      function Container() {
        this._sections = [];
      }

      Container.prototype.add = function(section) {
        if (section instanceof Section) {
          return this._sections.push(section);
        } else {
          throw new Error("The container can only have sections");
        }
      };

      Container.prototype.getData = function() {
        var section, _i, _len, _ref, _results;
        _ref = this._sections;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          section = _ref[_i];
          _results.push(section.getData());
        }
        return _results;
      };

      return Container;

    })();
  });

}).call(this);
