// Generated by CoffeeScript 1.7.1
(function() {
  define(["todo-list/item"], function(Item) {
    var Section;
    return Section = (function() {
      function Section(_title) {
        this._title = _title;
      }

      Section._items = {};

      Section.prototype.add = function(item) {
        return console.log('add item');
      };

      Section.prototype.getData = function() {
        var item, _i, _len, _ref, _results;
        _ref = this._items;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          _results.push(item.getData());
        }
        return _results;
      };

      return Section;

    })();
  });

}).call(this);
